### ISSUE TITLE
got some bug

### ISSUE THREAD

**Issue by NBTailee** [georgian-io/Multimodal-Toolkit#72]
i cant load my dataset and i cant fixed it :((
![Screenshot 2024-04-27 190836](https://github.com/georgian-io/Multimodal-Toolkit/assets/87483288/6cf530d5-7be9-486c-bbdc-9ceec514e117)
![Screenshot 2024-04-27 190855](https://github.com/georgian-io/Multimodal-Toolkit/assets/87483288/89fdcf07-ed24-47f5-b978-fe82ad7d2a46)
![Screenshot 2024-04-27 190903](https://github.com/georgian-io/Multimodal-Toolkit/assets/87483288/1c6c3669-188a-4c27-959c-f4dcf65685fd)

**Comment by anirbandey303** [comment]
It is throwing a "KeyError". Could you double check the column names provided for text_cols, numerical _cols and categorical _cols exactly matches with your column names in your dataset?

**Comment by NBTailee** [comment]
here is my columns name
![Screenshot 2024-04-27 213710](https://github.com/georgian-io/Multimodal-Toolkit/assets/87483288/d8d0f01e-2573-43e7-8ce6-7506c442813b)
![Screenshot 2024-04-27 213734](https://github.com/georgian-io/Multimodal-Toolkit/assets/87483288/5022c8be-223c-4f32-a216-0542cbe36b17)

**Comment by NBTailee** [comment]
@anirbandey303  as you can see my  columns match with the code so i dont know where the bug is and how to fix it

**Comment by akashsaravanan-georgian** [comment]
Hi @NBTailee, thanks for raising the issue. Let's see if we can figure out what the issue is and how to fix it! I can put in a fix to the library after that. 

It looks like the error is arising from the model attempting to use categorical features but you aren't using categorical features. Can you add the following parameter to your `load_data_from_folder()` call? `categorical_encode_type=None`

**Comment by NBTailee** [comment]
@akashsaravanan-georgian thanks for ur help
